#!/bin/bash

command=$1
dest=$2
echo -e "\n$command"
path=$(which "$command" 2>/dev/null)
if [ -n "$path" ]; then
  echo "Copy command \"$path\""
  copy_link_file $path $dest
  copy_libraries $path $dest
else
  echo "El comando $command no está disponible en el sistema."
fi
