#!/bin/bash
path="$1"
dest="${2:-/opt-A}" # Si no se pasa el segundo argumento, se usa "/opt-A"
[[ "${dest: -1}" == "/" ]] && dest="${dest%/}"
[[ "${dest:0:1}" == "." ]] && dest="$(realpath "$PWD/${dest}")"

# Verificar si el archivo o directorio existe
dest_file=$dest$(cd "$(dirname "$source")" >/dev/null 2>&1 && pwd)/$(basename $path)
if [ ! -e "$path" ]; then
  echo "El archivo \"$path\" no existe"
elif [ -e $dest_file ]; then
  echo "El archivo \"$dest_file\" ya existe"
else
  echo -e "\tcp -a \"$path\" \"$dest_file\""
  dest_dir=$(dirname $dest_file)
  [ ! -e $dest_dir ] && mkdir -p $dest_dir

  cp -a "$path" "$dest_file"
  echo -e "\t"cp -a "$path" "$dest_file"

  # Comprobar si el archivo es un enlace simbólico
  if [ -L "$path" ]; then
    # Obtener la ruta a la que apunta el enlace simbólico
    target=$(readlink "$path")
    if [[ "$target" != /* ]]; then
      # Accedemos a la ruta del fichero original para respetar la ruta relativa del enlace
      cd $(dirname "$path")
      file=$(basename $target)
      # Accedemos ahora a la ruta relativa
      cd $(dirname $target)
      target=$PWD/$file
    fi

    echo -e "\tLink found, following link --> \"$target\""
    # Llamar al script nuevamente con la nueva ruta (seguimos el enlace simbólico)
    "$0" "$target" "$dest"
  fi
fi
