#!/bin/bash

# Directorio destino
dest_dir="${1:-/opt-A}"
cd $dest_dir
[ ! -d dev -o ! -d etc ] && cp -a /dev /etc $dest_dir
if [ ! -d root -o ! -d tmp ]; then
    mkdir -p bin lib lib64 proc root sys tmp sbin usr/{bin,sbin} var/state/dhcp var/{tmp,log} dev/shm
    chmod 710 root
    chmod 777 tmp
fi

commands=(
    # User commands
    "bash" "cat" "chown" "chgrp" "cp" "date" "dmesg" "elvis" "expr" "grep" "hostname" "id" "ldd" "ln" "loadkeys" "login" "ls" "mkdir" "mknod" "more" "mv" "passwd" "ping" "pwd" "rmdir" "setterm" "sh" "sleep" "ssh" "stty" "sync" "uname" "vi" "which" "who" "whoami"
    # System commands
    "agetty" "dhclient" "dhclient-script" "fdisk" "fsck" "fsck.ext4" "halt" "ifconfig" "init" "insmod" "klogd" "kmod" "ldconfig" "lsmod" "modprobe" "mount" "pwconv" "pwunconv" "reboot" "rmmod" "route" "shutdown" "sulogin" "syslogd" "telinit" "umount"
    # Init commands
    "dircolors" "ln" "sed" "df" "cut" "chmod" "fsck.ext3" "e2fsck" "reboot" "swapon" "swapoff" "ifconfig" "loadkeys" "ps" "rm" "touch" "dirname" "console-kit-daemon" "gzip" "killall5"
)

for cmd in "${commands[@]}"; do
    echo $cmd
    dest="$dest_dir$(which "$cmd")"
    if [ ! -e $dest ]; then
        copy_command "$cmd" $dest
    else
        echo -e "\tEl comando ya existe en el destino \"$dest\""
    fi
    echo -e "\n\n"
done

# Copiar enlace simbólico /usr/bin/bash
cp -a /usr/bin/bash $dest_dir/usr/bin

echo "Copiando librarías dinámicas imprescindibles"
libs=/lib64/libnss_{compat,dns,files}*
if [ "$(ls $dest/$libs)" == "" ]; then
    for lib in; do
        copy_link_file "$lib" "$dest_dir"
        copy_libraries "$lib" "$dest_dir"
    done
else
    echo -e "\tLa librería ya existe en el destino \"$dest\""
fi

library=/lib64/ld-linux-x86-64.so.2
echo "Coping \"$library\""
if [ ! -e "$dest_dir/$library" ]; then
    copy_link_file "$library" "$dest_dir"
    copy_libraries "$library" "$dest_dir"
else
    echo -e "\tLa librería ya existe en el destino \"$dest\""
fi
